package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import javax.swing.text.html.HTML;

public class TelaLogin extends javax.swing.JFrame implements Runnable {

		
	
	private JPanel contentPane;
    TelaJogo jbingo;
      
    public Socket socket;
    public TelaLogin(Socket socket) {
    	
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 397, 333);
		contentPane = new JPanel();
		contentPane.setBackground(new Color(255, 255, 204));
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
    	
        initComponents();
        this.socket = socket;
        
        jbingo = new TelaJogo(this.socket);
    }
    int[] numeros = new int[24];
    boolean jogo = true;
    String numero = "";
    
    
    DataInputStream din;
    DataOutputStream dou;
    
    //recebe os numeros sorteados
    @Override
    public void run(){  
        try {
            din = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        while(jogo){
            try {
                numero = din.readUTF();
                    System.out.println(numero);
                Integer.parseInt(numero);
                Frame[] frames = Frame.getFrames();
                for (Frame frame : frames){
                    frame.setTitle("Numero: "+numero);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "O usuario "+numero+" venceu");
                this.setVisible(true);
                Frame[] frames = Frame.getFrames();
                for (Frame frame : frames){
                    frame.setTitle("Close");
                }
                jogo = false;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblEmail.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblEmail.setBounds(36, 43, 63, 14);
		contentPane.add(lblEmail);
		
		
		lblRecordesDoMs = new javax.swing.JLabel("Recordes do M\u00EAs");
		lblRecordesDoMs.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblRecordesDoMs.setBounds(130, 165, 127, 14);
		contentPane.add(lblRecordesDoMs);
		
        lblSenha = new javax.swing.JLabel();
        lblSenha.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblSenha.setBounds(36, 80, 63, 14);
		contentPane.add(lblSenha);
		
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordField.setBounds(93, 79, 231, 20);
		contentPane.add(jPasswordField);
		
        textFieldEmail = new javax.swing.JTextField();
        textFieldEmail.setBounds(93, 42, 231, 20);
		contentPane.add(textFieldEmail);
		textFieldEmail.setColumns(10);
        
        buttonEntrar = new javax.swing.JButton();
        
        btnCadastrar = new javax.swing.JButton();
        btnCadastrar.setFont(new Font("Tahoma", Font.BOLD, 11));
		btnCadastrar.setBounds(267, 124, 103, 23);
		contentPane.add(btnCadastrar);
        
        buttonCancelar = new javax.swing.JButton();
        buttonCancelar.setFont(new Font("Tahoma", Font.BOLD, 11));
        buttonCancelar.setBounds(139, 124, 103, 23);
		contentPane.add(buttonCancelar);
		
		JLabel lblNome = new JLabel("Nome");
		lblNome.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblNome.setBounds(118, 190, 46, 14);
		contentPane.add(lblNome);
		
		JLabel lblVitrias = new JLabel("Vit\u00F3rias");
		lblVitrias.setFont(new Font("Tahoma", Font.BOLD, 11));
		lblVitrias.setBounds(221, 191, 46, 14);
		contentPane.add(lblVitrias);
		
		JLabel lblNewLabel = new JLabel("-");
		lblNewLabel.setBounds(118, 215, 93, 14);
		contentPane.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("-");
		lblNewLabel_1.setBounds(118, 236, 93, 14);
		contentPane.add(lblNewLabel_1);
		
		JLabel lblNewLabel_2 = new JLabel("-");
		lblNewLabel_2.setBounds(118, 257, 93, 14);
		contentPane.add(lblNewLabel_2);
		
		JLabel lblNewLabel_3 = new JLabel("-");
		lblNewLabel_3.setBounds(221, 216, 63, 14);
		contentPane.add(lblNewLabel_3);
		
		JLabel lblNewLabel_4 = new JLabel("-");
		lblNewLabel_4.setBounds(221, 236, 63, 14);
		contentPane.add(lblNewLabel_4);
		
		JLabel lblNewLabel_5 = new JLabel("-");
		lblNewLabel_5.setBounds(221, 257, 63, 14);
		contentPane.add(lblNewLabel_5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );


        lblEmail.setText("Email :");

        lblSenha.setText("Senha :");

        jPasswordField.setText("");

        textFieldEmail.setText("");

        buttonEntrar.setText("Login");
        buttonEntrar.setFont(new Font("Tahoma", Font.BOLD, 11));
        buttonEntrar.setBounds(10, 124, 103, 23);
		contentPane.add(buttonEntrar);
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastro");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

    }
    
    
    //CANCELAR
    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
        //this.setVisible(false);
    }                                        
    
    //LOGIN
    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        String go = "";
        int stat = 0;
        String goo = "";
        //
        //
        //
        try{
            dou = new DataOutputStream(socket.getOutputStream());
            din = new DataInputStream(socket.getInputStream());
            dou.writeUTF("1");
            sleep(100);
            dou.writeUTF(textFieldEmail.getText());
            sleep(100);
            dou.writeUTF(jPasswordField.getText());
            sleep(100);
            
            
            go = din.readUTF();
            if(go.equals("1")){
                for(int i = 0; i < 24; i++){
                    try {
                        numeros[i] = Integer.parseInt(din.readUTF());
                    } catch (IOException ex) {

                    } 
                }

                jbingo.jToggleButton6.setText(""+numeros[0]);
                jbingo.jToggleButton7.setText(""+numeros[1]);
                jbingo.jToggleButton8.setText(""+numeros[2]);
                jbingo.jToggleButton9.setText(""+numeros[3]);
                jbingo.jToggleButton10.setText(""+numeros[4]);
                jbingo.jToggleButton11.setText(""+numeros[5]);
                jbingo.jToggleButton12.setText(""+numeros[6]);
                jbingo.jToggleButton13.setText(""+numeros[7]);
                jbingo.jToggleButton14.setText(""+numeros[8]);
                jbingo.jToggleButton15.setText(""+numeros[9]);
                jbingo.jToggleButton16.setText(""+numeros[10]);
                jbingo.jToggleButton17.setText(""+numeros[11]);
                jbingo.jToggleButton19.setText(""+numeros[12]);
                jbingo.jToggleButton20.setText(""+numeros[13]);
                jbingo.jToggleButton21.setText(""+numeros[14]);
                jbingo.jToggleButton22.setText(""+numeros[15]);
                jbingo.jToggleButton23.setText(""+numeros[16]);
                jbingo.jToggleButton24.setText(""+numeros[17]);
                jbingo.jToggleButton25.setText(""+numeros[18]);
                jbingo.jToggleButton26.setText(""+numeros[19]);
                jbingo.jToggleButton27.setText(""+numeros[20]);
                jbingo.jToggleButton28.setText(""+numeros[21]);
                jbingo.jToggleButton29.setText(""+numeros[22]);
                jbingo.jToggleButton30.setText(""+numeros[23]);


                jbingo.setVisible(true);
                this.setVisible(false);

                jbingo.revalidate();
                jbingo.repaint();

                stat = 1;
                
                TelaLogin obj=new TelaLogin(socket);  
                Thread tobj =new Thread(obj);  
                tobj.start();
     
            }
            else{
                JOptionPane.showMessageDialog(null,"Usuario ou senha incorretos");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }                                        

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        TelaCadastro jcad = new TelaCadastro(this.socket);
        jcad.setVisible(true);
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin(new Socket()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblRecordesDoMs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField textFieldEmail;
    // End of variables declaration                   
}
