/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.Socket;
import java.io.DataOutputStream;
import static java.lang.Thread.sleep;

import java.awt.Color;
import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

@SuppressWarnings("serial")
public class TelaJogo extends javax.swing.JFrame{
 
	private JPanel contentPane;
	
    public Socket socket;
    DataOutputStream dou;
    public String jogo = "";
    
    public TelaJogo(Socket socket) {
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 338, 390);
		contentPane = new JPanel();
		contentPane.setBackground(new Color(255, 255, 204));
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		initComponents();
		
        this.socket = socket;
        //this.setTitle("Bingo");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton1.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton1.setBounds(10, 11, 53, 45);
        contentPane.add(jToggleButton1);
        
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton2.setBounds(73, 11, 53, 45);
        contentPane.add(jToggleButton2);
		
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton3.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton3.setBounds(136, 11, 53, 45);
        contentPane.add(jToggleButton3);
        
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton4.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton4.setBounds(199, 11, 53, 45);
        contentPane.add(jToggleButton4);
	
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton5.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton5.setBounds(262, 11, 53, 45);
        contentPane.add(jToggleButton5);
        
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton6.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton6.setBounds(10, 67, 53, 45);
        contentPane.add(jToggleButton6);
		
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton7.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton7.setBounds(73, 67, 53, 45);
        contentPane.add(jToggleButton7);
        
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton8.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton8.setBounds(136, 67, 53, 45);
        contentPane.add(jToggleButton8);
        
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton9.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton9.setBounds(199, 67, 53, 45);
        contentPane.add(jToggleButton9);
        
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton10.setFont(new Font("Tahoma", Font.BOLD, 11));
        jToggleButton10.setBounds(262, 67, 53, 45);
        contentPane.add(jToggleButton10);
		
		jToggleButton11 = new javax.swing.JToggleButton();
		jToggleButton11.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton11.setBounds(10, 123, 53, 45);
		contentPane.add(jToggleButton11);
		
		jToggleButton12 = new javax.swing.JToggleButton();
		jToggleButton12.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton12.setBounds(10, 179, 53, 45);
		contentPane.add(jToggleButton12);
		
		jToggleButton13 = new javax.swing.JToggleButton();
		jToggleButton13.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton13.setBounds(10, 235, 53, 45);
		contentPane.add(jToggleButton13);
		
		jToggleButton14 = new javax.swing.JToggleButton();
		jToggleButton14.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton14.setBounds(73, 123, 53, 45);
		contentPane.add(jToggleButton14);
		
		 jToggleButton20 = new javax.swing.JToggleButton();
		jToggleButton20.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton20.setBounds(73, 179, 53, 45);
		contentPane.add(jToggleButton20);
		
		jToggleButton15 = new javax.swing.JToggleButton();
		jToggleButton15.setFont(new Font("Tahoma", Font.BOLD, 5));
		jToggleButton15.setBounds(136, 123, 53, 45);
		contentPane.add(jToggleButton15);
		
		jToggleButton17 = new javax.swing.JToggleButton();
		jToggleButton17.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton17.setBounds(199, 123, 53, 45);
		contentPane.add(jToggleButton17);
		
		jToggleButton18 = new javax.swing.JToggleButton();
		jToggleButton18.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton18.setBounds(262, 123, 53, 45);
		contentPane.add(jToggleButton18);
		
		jToggleButton19 = new javax.swing.JToggleButton();
		jToggleButton19.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton19.setBounds(136, 179, 53, 45);
		contentPane.add(jToggleButton19);
		
		jToggleButton21 = new javax.swing.JToggleButton();
		jToggleButton21.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton21.setBounds(199, 179, 53, 45);
		contentPane.add(jToggleButton21);
		
		jToggleButton22 = new javax.swing.JToggleButton();
		jToggleButton22.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton22.setBounds(262, 179, 53, 45);
		contentPane.add(jToggleButton22);
		
		jToggleButton23 = new javax.swing.JToggleButton();
		jToggleButton23.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton23.setBounds(73, 235, 53, 45);
		contentPane.add(jToggleButton23);
		
		jToggleButton24 = new javax.swing.JToggleButton();
		jToggleButton24.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton24.setBounds(136, 235, 53, 45);
		contentPane.add(jToggleButton24);
		
		jToggleButton25 = new javax.swing.JToggleButton();
		jToggleButton25.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton25.setBounds(199, 235, 53, 45);
		contentPane.add(jToggleButton25);
		
		jToggleButton16 = new javax.swing.JToggleButton();
		jToggleButton16.setFont(new Font("Tahoma", Font.BOLD, 11));
		jToggleButton16.setBounds(262, 235, 53, 45);
		contentPane.add(jToggleButton16);
		
		JLabel lblNmeroSorteado = new JLabel("N\u00FAmero Sorteado:");
		lblNmeroSorteado.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblNmeroSorteado.setBounds(73, 311, 137, 14);
		contentPane.add(lblNmeroSorteado);
		
		JLabel lblXx = new JLabel("xx");
		lblXx.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblXx.setBounds(220, 311, 46, 14);
		contentPane.add(lblXx);
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jToggleButton1.setText("B");

        jToggleButton2.setText("I");

        jToggleButton3.setText("N");

        jToggleButton4.setText("G");

        jToggleButton5.setText("O");

        jToggleButton6.setText("0");

        jToggleButton7.setText("0");

        jToggleButton8.setText("0");

        jToggleButton9.setText("0");

        jToggleButton10.setText("0");

        jToggleButton11.setText("0");

        jToggleButton12.setText("0");

        jToggleButton13.setText("0");

        jToggleButton14.setText("0");

        jToggleButton15.setText("BINGO");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        jToggleButton16.setText("0");

        jToggleButton17.setText("0");

        jToggleButton18.setText("0");

        jToggleButton19.setText("0");

        jToggleButton20.setText("0");

        jToggleButton21.setText("0");

        jToggleButton22.setText("0");

        jToggleButton23.setText("0");

        jToggleButton24.setText("0");

        jToggleButton25.setText("0");

        jToggleButton26.setText("0");

        jToggleButton27.setText("0");

        jToggleButton28.setText("0");

        jToggleButton29.setText("0");

        jToggleButton30.setText("0");
    }

                             

    //BINGOOOOOOO
    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        try{
        dou = new DataOutputStream(socket.getOutputStream());
        dou.writeUTF("9");
        sleep(100);
        }
        catch(Exception e){
            
        }
    }                                               
    
    private void formFocusGained(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        //System.err.println("GAINNNNN");
    }                                

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {                                    
        // TODO add your handling code here:
        if(!this.jogo.equals(this.getTitle())){
            this.jogo = this.getTitle();
            //System.out.println(""+rodadas);
        }
        if(this.getTitle().equals("Close")){
            this.setVisible(false);
        }
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        //=============================
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo(new Socket()).setVisible(true);
            }
        });
        
        //new JFBingo();
    }


    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JToggleButton jToggleButton10;
    public javax.swing.JToggleButton jToggleButton11;
    public javax.swing.JToggleButton jToggleButton12;
    public javax.swing.JToggleButton jToggleButton13;
    public javax.swing.JToggleButton jToggleButton14;
    public javax.swing.JToggleButton jToggleButton15;
    public javax.swing.JToggleButton jToggleButton16;
    public javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    public javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JToggleButton jToggleButton20;
    public javax.swing.JToggleButton jToggleButton21;
    public javax.swing.JToggleButton jToggleButton22;
    public javax.swing.JToggleButton jToggleButton23;
    public javax.swing.JToggleButton jToggleButton24;
    public javax.swing.JToggleButton jToggleButton25;
    public javax.swing.JToggleButton jToggleButton26;
    public javax.swing.JToggleButton jToggleButton27;
    public javax.swing.JToggleButton jToggleButton28;
    public javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    public javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    public javax.swing.JToggleButton jToggleButton6;
    public javax.swing.JToggleButton jToggleButton7;
    public javax.swing.JToggleButton jToggleButton8;
    public javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration                   
}
